apiVersion : apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: gcr.io/fillcraft-swards/swards_img:latest
        imagePullPolicy: Always
        name: hello-world
        ports:
        - containerPort: 4200
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
    name: hello-world
spec:
    type: LoadBalancer
    ports:
    - port: 4200
      targetPort: 4200
      nodePort: 3000
    selector:
        app: hello-world
---

